[connections.snowflake]
account = "PBTHOTC-KQB36718"
user = "UlrichK"
password = "SNOWF#jcl53787"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
